TARGET:=paint64
include ../ch32v003fun/ch32v003fun.mk
clean:
	rm -f $(TARGET).elf $(TARGET).hex $(TARGET).bin $(TARGET).map $(TARGET).lst $(TARGET).o $(TARGET).d $(TARGET).srec $(TARGET).sym $(TARGET).lss $(TARGET).eep $(TARGET).eep.hex $(TARGET).eep.bin $(TARGET).eep.map $(TARGET).eep.lst $(TARGET).eep.o $(TARGET).eep.d $(TARGET).eep.srec $(TARGET).eep.sym $(TARGET).eep.lss
