TARGET:=savepaint
#ADDITIONAL_C_FILES:=../ch32v003fun/lib_i2c.c
include ../ch32v003fun/ch32v003fun.mk
clean:
	rm -f $(TARGET).elf $(TARGET).hex $(TARGET).bin $(TARGET).map $(TARGET).lst \
		$(TARGET).o $(TARGET).d $(TARGET).srec $(TARGET).sym $(TARGET).lss

.PHONY: clean
